{% set version = "1.56.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pamr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pamr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pamr/pamr_{{ version }}.tar.gz
  sha256: 29046c761d1999f34c6eb69cab5484985cc5c309e3e9d60891cf36d5febbfc58

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("c") }}                # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-cluster
    - r-survival
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-cluster
    - r-survival

test:
  commands:
    - $R -e "library('pamr')"           # [not win]
    - "\"%R%\" -e \"library('pamr')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=pamr
  license: GPL-2.0-only
  summary: Some functions for sample classification in microarrays.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr

# Package: pamr
# Title: Pam: Prediction Analysis for Microarrays
# Version: 1.56.1
# Author: T. Hastie, R. Tibshirani, Balasubramanian Narasimhan, Gil Chu
# Description: Some functions for sample classification in microarrays.
# Maintainer: Rob Tibshirani  <tibs@stanford.edu>
# Depends: R (>= 2.10), cluster, survival
# License: GPL-2
# Packaged: 2019-04-21 11:21:24 UTC; ripley
# Repository: CRAN
# NeedsCompilation: yes
# Date/Publication: 2019-04-22 06:58:41 UTC
