# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "IQhi84XbCbwJ1PmD9BBoqgtXTtn0jMnYGzTLU2WPdiRRLOJs8cJGmPjFen6XwxJWsF0oM0zi8ybIxQHyb6ywFNR3BmR7+HjV7jR/LLyHcl7eoOahz3HMIPvnofOikah0VC4luGBj65z3iKpgcRVrqrrgk00LLNAoKcyYsHIWzOkLPWwQ0Q+GlYIeF4x++A9pGWleLh1jqqrBxBp93YKIELZ48HkHnHu2z+X2EEwiwPrbWKXiPxFkSFpLjIKYb5o/Yw/+Ius6ssMTZawS3vfaq/lgIGw1cMiUXb8KmOJNv5Pr48ddR6FSeEGFpQbhhBhEykyk/F/mMqp/ViMw43r/OshRmNQhrpVmo+3zIWs4ThmZ2cXTgEYDUkNJxNX1Itgq6acTZ+DSpUE+3mU17ZtLu6R7oBcz3oJ3F7Q0xVYmgroyYvFBuUp5x89azAp1N7ovUP5vJvkiwB7Xg8MkcjrWo/13Wbd7dJ/nNEIjEpnvh/OijOGcRKHL9KnZ12xvBWYVWck9U3iW6kbQcLWDS9aZjZM5iHikdXFXJktZosRmxR7H322wM76J25NUXAsqMa6mLgOsKMAE8Q6QDTBmj3A9VqexUNbF48ZAuynvKWfBCz5HY/mcdDJw5dk0cdhzP8bRBVy3j1m45WqR1DZytRjEp7OSuM9A+NZ9kOKcTMhEoKs="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
