travis:
  secure:
    BINSTAR_TOKEN: Y6iu7oiYZAZiiiKrxyycdyDwBmpDdjbzgdFHg+mFCUo9DhMlkHNXO0N4V1P2RdxHpYfgyKDeEwDI/G84c69PdlNp+Z3XcYOUcDCMPTxg5xK41tOZ8nVp/h3KYBcT3cbm4TfbaumVBnKZkdnT8x8nVEIcZ/tMZyrklvLlNfKiN7oqGGEDK/QffrcwUVTH5f9gip5qA6QDVis6hVVbFEysB4CWFEEwB/i/USV/8PMoqOGb+nIs3cPACgJoNbgls/UbohHgKMcBiApJGlGaN0vPGGoZyOx747WvQiIob6kxMYovB1yE5Tc1dLJ1oglPm0njvtnPwVUSfec1VFXoGyqGkcbap89vLx3HCA+HbXeubHdz9wTTBvYxPkUl9/Y2r1j1U3T94gSopqILD9MD0ABgXJZkSLVxXOBsgqTh6xiTOFN5bJLonJCvRKpeJLjGyARocOggBZaZJrHGx0bcRaxGXXktvTQdNrdF8F5SrmorALAvfuZSBX6ZQdk01rwhY+HgCe/bui53CxqHooZpNIFT0m/jWgln/mugc4Aw6+MLYqsJ4gD1XjWyC8PNSTE2jUFv5u9mirInKx5eo83iAHhMvFxoj4L/WdYVgJ+Dz+kStGSUM8wvALf0YRCuGSeBPRAui+hSxppBEDZx2zen19DuZXTJ9dW5k2jETA4MINJ85Ko=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
