travis:
  secure:
    BINSTAR_TOKEN: wxw5xkCb/ljdCXtiFTT69ssi2nkFmnSC/jWBtlA9hleWZ/ZhGEihclfCpYYNtF3xAfuaMd+h1qx3xTtiSEAburjt6Nv9LB6s9XkmDyvcGCsWuecpMAjPY2nye9kT7JgIrPp6BrOut6yrjwT9dzcQ9CwT31QkBqbRXxsmElbXissXAlyw8hQhM2mqAuyjeLYFUEQtzJGc1ApItxoNmbi0y1Dv3pbm/rYXdFZUQ6+8fn4uZf7wx/hKDqLLn/jUr/EiH0kEkaPAdd3/PRSV+m+h8YHLN/QaTmB/Xs3DLwH4Rt75waKl0vr1m8D9vgFXzeG7sFlBpiNn+x3F585hzbG6qPDLkbXZvLy+XrSJD8PvXCE93C1UtvWwlFMANXawmf3dJueb/WB7ZRBmwRnFqdp3qU4a8yzp/QeClJqWlK/PuW5eDd/MxVYYVD2Qtk4qrhQWlvCWzHYFpzgBQBepiNZ3XbMjhcXp091pTLq3Jbha4IvfGbMglAFxFHzK2RmkZJd0QYs/rfG3fFM7dJQLqAkNCyQyxs235rTVlm9gRm1Rnp0mbsriNBtv4Py70XKYSZbM3P5OZSAV4Qzubfxu1FyM5bf+XQdawNl7lZ8FkjqGBQNaBgjc2JEPGoJS5YuD3TmqcEKlArlLp0rSxMpP3uCodf0qFpnRHtqw0xFTQp2Huwo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
