travis:
  secure:
    BINSTAR_TOKEN: IQhi84XbCbwJ1PmD9BBoqgtXTtn0jMnYGzTLU2WPdiRRLOJs8cJGmPjFen6XwxJWsF0oM0zi8ybIxQHyb6ywFNR3BmR7+HjV7jR/LLyHcl7eoOahz3HMIPvnofOikah0VC4luGBj65z3iKpgcRVrqrrgk00LLNAoKcyYsHIWzOkLPWwQ0Q+GlYIeF4x++A9pGWleLh1jqqrBxBp93YKIELZ48HkHnHu2z+X2EEwiwPrbWKXiPxFkSFpLjIKYb5o/Yw/+Ius6ssMTZawS3vfaq/lgIGw1cMiUXb8KmOJNv5Pr48ddR6FSeEGFpQbhhBhEykyk/F/mMqp/ViMw43r/OshRmNQhrpVmo+3zIWs4ThmZ2cXTgEYDUkNJxNX1Itgq6acTZ+DSpUE+3mU17ZtLu6R7oBcz3oJ3F7Q0xVYmgroyYvFBuUp5x89azAp1N7ovUP5vJvkiwB7Xg8MkcjrWo/13Wbd7dJ/nNEIjEpnvh/OijOGcRKHL9KnZ12xvBWYVWck9U3iW6kbQcLWDS9aZjZM5iHikdXFXJktZosRmxR7H322wM76J25NUXAsqMa6mLgOsKMAE8Q6QDTBmj3A9VqexUNbF48ZAuynvKWfBCz5HY/mcdDJw5dk0cdhzP8bRBVy3j1m45WqR1DZytRjEp7OSuM9A+NZ9kOKcTMhEoKs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
