travis:
  secure:
    BINSTAR_TOKEN: cCnu03OYZj1Vb82yylByWggJoP8qx1bU3Mjo+GAAt7Vy0WBp5qyzFAKFExSAbHVktgoWwb4K9rAEEZcJUvhTLT9WDn3oitDFS3opXpaE+ahE8vhxpCkLmjINmeBC2vy18Hgp+35Rs8ev7JhpTOqIgbrVGSP+CvEIYxmaoGZYIIwidEVAhR9dGlRlBk/c8YH7q81nS8j5WIpTIsksjwrmgaPlHEckWtzz3RcsrOMXYmZQLFp2+eIzhgFW4IbuTCySBcXdDaL0xJZYm2/8rojqm28+KcWXvdfiY0gOiNq1Mqxog19ycvfxH6QlTrLsOWI1NSOwbfQ7rEfRJkXXeUBOmjXAW4qOlbJ2xzg7TqePCJSc5ZomF4053SuRXGeitZFCGxuhdDELxRZ7j4GebVSxEWKWEgseiq1xno52xihrXu3mr5J73B1+SCdWSwgiCwlaNk0KQWZIRoGYpIVcEMntorK6Gh+LGaouu2SyNDDtF6c0aTrCTTrn+hQN2TXFXwNpKuPBX53phtqPB2Tranv7iq/zr6FDWCS+sXu7R5WmonGrEU+q3Lt4Z9+8DxlTctFsLZuZ8OjNUx8vJSf3WZUJwVX54NHwXlm+YKnfN07BhK8RNrGiOVdlbhiDZW235rTk8aAY6OqDNZUZH9WrNdtCt3ZDmZwi/z6iZDsa+5O/8sA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
