travis:
  secure:
    BINSTAR_TOKEN: ThW/jF3jjHFAGtgpw9fTk0K21d/J2rooXCXu3eGAJH6LIiEiV6zcZiTXnv/rCc9Z6oqTAffcGxBbK4i43arsfxFkPZct5GRX5B6LWxrdirWkoNDRY5K4yVD079ISvdJ8FsGk6XHQn3YeIj7W999ZTbzkFFGuGv/jkoC349MiVK5FT7K3qsJcEJzPCNfZDRsllN+TKV5Ox2Z0dNP/16WAKJzI4CIhK0KXu/hcIqV79FGdnYt1M48tDN9t7owgfI8XZ7+yJu8fHk7uCpYdMwF9eL6CFx7ZCMKp8qBcoE6JmMfsbdGeYSGI/t37mFbbggMiWDUyMwxEMuCB7QIT/J+8D35dWeFlxN1LP8+lexcp1I3jAmGKtLWxFv6inxRTpezJiNH4lZ3epOPaqUaDOqalDfUReUql1TmmWKeDs9y8qJnkoNOswv1VrXg7wR4BaZ5De9azgHrvKydwyyPujmecK+a8mlS+kqhLzGoIerfNelaBs/wxlxJybZuWbFv9fTO0QwbZK4HnU27LxGi3PfpdlQ3kiMVxZkJ6ygPodyfyUjxhWXOCXQpesi4D6BmIlKwE36I5xAuN7G8DPNupb3K0m0eegMRMBcUv/0IpjDpc4ik4Gag3fh2PXxbjyBwa596iP4yqgIAs/gTqpia1ITh8zddOkI8KLtKq1IqAwKqpJjA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
