travis:
  secure:
    BINSTAR_TOKEN: QJbKnDqGqxuxO7G8YPq0aWSvqoFxfJ6Rmm9JOIuZZ4fFwwM56r14N5YXwsqlNQ5N1RzJi0G8DvoYa5rwx7uu03a6YR8Q3tUJAU18tqMSU3sEYYguVILDeBTtR4x0fetEsNq1NpfC1wzNw1gv41j776XfB7D+Qmp3PBJ71dvJ6EVbOPX8xjomceFCJcpO1JF0/junfUfmhjwyB/Qau/UGWTam7pshdGRKjTRgjGDIXjZsd3eM23Z7ni+dGNzn073qB0OnCHCJJ0JoH+UhzgfqGOhvAfBKpuKzQAsaZAhi+oCheN2TtLVk9apaSkLeIW9xuW8cd/j8c+Coa8OwRMbAbNLrjA4CpFLVt9IdQsr1D0aoENZXYTD22X/SPQpIAuvXakOuzTEAufHraJKxjCxzBj87QDKvPs5QiIlsZ2FC5tcDUTHdEAVZWVoULFD8yesgJJen+1xQHsh6DoWWLTwgVGoD8OCev92ftVz0mdxEY60ePR9FVEmBOpHcyDKxdMiLSTk1rTViisoLafMsPGbD8NPexYijxaIyuDbZRC8W9OBUOPehqYY0v8CmRFVkCtkWHUAzWj8fsfGnFrYi0bPTp6Mx7krxkId6UMVfWdmFD/zDhJZQ8SOZXhRSlTLwHzT2ppsDkykZp1ea2iLK0ZGn/8Q3Bb+d/O68e8eRWqDLNa0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
